USER_AUDIO_FRAME = "USER_AUDIO_FRAME"
USER_SPEECH_START = "USER_SPEECH_START"
USER_SPEECH_PAUSE = "USER_SPEECH_PAUSE"
USER_SPEECH_END = "USER_SPEECH_END"
ASR_PARTIAL = "ASR_PARTIAL"
ASR_FINAL = "ASR_FINAL"
ASSISTANT_SPEECH_START = "ASSISTANT_SPEECH_START"
ASSISTANT_SPEECH_END = "ASSISTANT_SPEECH_END"
SCENE_CHANGED = "SCENE_CHANGED"

OUTPUT_PROPOSAL = "OUTPUT_PROPOSAL"
CONTROL_ACTION = "CONTROL_ACTION"
STATE_UPDATE = "STATE_UPDATE"

PLAY_TTS = "PLAY_TTS"
PLAY_BACKCHANNEL = "PLAY_BACKCHANNEL"
PLAY_SFX = "PLAY_SFX"
STOP_TTS = "STOP_TTS"
DUCK_AUDIO = "DUCK_AUDIO"
SET_AMBIENCE = "SET_AMBIENCE"
FADE_OUT = "FADE_OUT"
QUEUE = "QUEUE"
CANCEL = "CANCEL"

INPUT_EVENTS = {
    USER_AUDIO_FRAME,
    USER_SPEECH_START,
    USER_SPEECH_PAUSE,
    USER_SPEECH_END,
    ASR_PARTIAL,
    ASR_FINAL,
    ASSISTANT_SPEECH_START,
    ASSISTANT_SPEECH_END,
    SCENE_CHANGED,
}

AGENT_OUTPUT_EVENTS = {
    OUTPUT_PROPOSAL,
    CONTROL_ACTION,
    STATE_UPDATE,
}

ORCHESTRATOR_OUTPUT_EVENTS = {
    PLAY_TTS,
    PLAY_BACKCHANNEL,
    PLAY_SFX,
    STOP_TTS,
    DUCK_AUDIO,
    SET_AMBIENCE,
    FADE_OUT,
    QUEUE,
    CANCEL,
}

__all__ = [
    "AGENT_OUTPUT_EVENTS",
    "ASR_FINAL",
    "ASR_PARTIAL",
    "ASSISTANT_SPEECH_END",
    "ASSISTANT_SPEECH_START",
    "CANCEL",
    "CONTROL_ACTION",
    "DUCK_AUDIO",
    "FADE_OUT",
    "INPUT_EVENTS",
    "ORCHESTRATOR_OUTPUT_EVENTS",
    "OUTPUT_PROPOSAL",
    "PLAY_BACKCHANNEL",
    "PLAY_SFX",
    "PLAY_TTS",
    "QUEUE",
    "SCENE_CHANGED",
    "SET_AMBIENCE",
    "STATE_UPDATE",
    "STOP_TTS",
    "USER_AUDIO_FRAME",
    "USER_SPEECH_END",
    "USER_SPEECH_PAUSE",
    "USER_SPEECH_START",
]
